TicketSystemDI/Controllers/PointController.cs
using Microsoft.AspNetCore.Mvc;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{
    public class PointController : Controller
    {
        private IRepository<Point> points { get; set; }
        public PointController(IRepository<Point> rep) => points = rep;

        public ViewResult Index()
        {
            var options = new QueryOptions<Point>
            {
                OrderBy = p => p.Name
            };
            return View(points.List(options));
        }

        [HttpGet]
        public ViewResult Add() => View();

        [HttpPost]
        public IActionResult Add(Point point)
        {
            if (ModelState.IsValid)
            {
                points.Insert(point);
                points.Save();

                TempData["msg"] = $"{point.Name} added to list of points";

                return RedirectToAction("Index");
            }
            else
            {
                return View(point);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(points.Get(id));
        }

        [HttpPost]
        public RedirectToActionResult Delete(Point point)
        {
            point = points.Get(point.PointId); // so can get point name for notification message

            points.Delete(point);
            points.Save();

            TempData["msg"] = $"{point.PointId} removed from list of points";

            return RedirectToAction("Index");
        }
    }
}

TicketSystemDI/Controllers/SprintController.cs
using Microsoft.AspNetCore.Mvc;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{
    public class SprintController : Controller
    {
        private IRepository<Sprint> sprints { get; set; }
        public SprintController(IRepository<Sprint> rep) => sprints = rep;

        public ViewResult Index()
        {
            var options = new QueryOptions<Sprint>
            {
                OrderBy = s => s.SprintNumber
            };
            return View(sprints.List(options));
        }

        [HttpGet]
        public ViewResult Add() => View();

        [HttpPost]
        public IActionResult Add(Sprint sprint)
        {
            if (ModelState.IsValid)
            {
                sprints.Insert(sprint);
                sprints.Save();

                TempData["msg"] = $"{sprint.SprintNumber} added to list of sprints";

                return RedirectToAction("Index");
            }
            else
            {
                return View(sprint);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(sprints.Get(id));
        }

        [HttpPost]
        public RedirectToActionResult Delete(Sprint sprint)
        {
            sprint = sprints.Get(sprint.SprintId); // so can get sprint number for notification message

            sprints.Delete(sprint);
            sprints.Save();

            TempData["msg"] = $"{sprint.SprintId} removed from list of sprints";

            return RedirectToAction("Index");
        }
    }
}

TicketSystemDI/Controllers/StatusController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{
    public class StatusController : Controller
    {
        private IRepository<Status> statuses { get; set; }
        public StatusController(IRepository<Status> rep) => statuses = rep;

        public ViewResult Index()
        {
            var options = new QueryOptions<Status>
            {
                OrderBy = p => p.Name
            };
            return View(statuses.List(options));
        }

        [HttpGet]
        public ViewResult Add() => View();

        [HttpPost]
        public IActionResult Add(Status status)
        {
            if (ModelState.IsValid)
            {
                statuses.Insert(status);
                statuses.Save();

                TempData["msg"] = $"{status.Name} added to list of statuses";

                return RedirectToAction("Index");
            }
            else
            {
                return View(status);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(statuses.Get(id));
        }

        [HttpPost]
        public RedirectToActionResult Delete(Status status)
        {
            status = statuses.Get(status.StatusId); // so can get status name for notification message

            statuses.Delete(status);
            statuses.Save();

            TempData["msg"] = $"{status.StatusId} removed from list of statuses";

            return RedirectToAction("Index");
        }
    }
}

TicketSystemDI/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using TicketSystem.Models;

namespace TicketSystem.Controllers
{
    public class TicketController : Controller
    {
        private IHttpContextAccessor http { get; set; }
        private ITicketUnitOfWork data { get; set; }

        public TicketController(ITicketUnitOfWork rep, IHttpContextAccessor ctx)
        {
            data = rep;
            http = ctx;
        }

        public RedirectToActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ViewResult Add()
        {
            this.LoadViewBag("Add");
            return View();
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            this.LoadViewBag("Edit");
            var c = this.GetTicket(id);
            return View("Add", c);
        }

        [HttpPost]
        public IActionResult Add(Ticket t)
        {
            string operation = (t.TicketId == 0) ? "Add" : "Edit";
            if (ModelState.IsValid)
            {
                if (t.TicketId == 0)
                    data.Tickets.Insert(t);
                else
                    data.Tickets.Update(t);
                data.Tickets.Save();

                string verb = (operation == "Add") ? "added" : "updated";
                TempData["msg"] = $"{t.Description} {verb}";

                return this.GoToTickets();
            }
            else
            {
                this.LoadViewBag(operation);
                return View();
            }
        }

        [HttpGet]
        public ViewResult Delete(int id)
        {
            var c = this.GetTicket(id);
            return View(c);
        }

        [HttpPost]
        public RedirectToActionResult Delete(Ticket t)
        {
            t = data.Tickets.Get(t.TicketId); // so can get ticket description for notification message

            data.Tickets.Delete(t);
            data.Tickets.Save();

            TempData["msg"] = $"{t.Description} deleted";

            return this.GoToTickets();
        }

        // private helper methods
        private Ticket GetTicket(int id)
        {
            var ticketOptions = new QueryOptions<Ticket>
            {
                Includes = "Sprint, Status, Point",
                Where = t => t.TicketId == id
            };
            return data.Tickets.Get(ticketOptions);
        }

        private void LoadViewBag(string operation)
        {
            ViewBag.Points = data.Points.List(new QueryOptions<Point>
            {
                OrderBy = p => p.PointId
            });
            ViewBag.Statuses = data.Statuses.List(new QueryOptions<Status>
            {
                OrderBy = s => s.Name
            });
            ViewBag.Sprints = data.Sprints.List(new QueryOptions<Sprint>
            {
                OrderBy = s => s.SprintNumber
            });

            ViewBag.Operation = operation;
        }

        private RedirectToActionResult GoToTickets()
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

TicketSystemDI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    <header class="bg-primary text-white text-center">
        <h1 class="m-3 p-3">Ticket System</h1>
    </header>
    <main>
        @RenderBody()
    </main>
</div>

<header>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-controller="Ticket" asp-action="Index" asp-route-id="">Show All Tickets</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Sprint" asp-action="Index">Show All Sprints</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Status" asp-action="Index">Show All Statuses</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Point" asp-action="Index">Show All Points</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    @if (TempData.ContainsKey("msg"))
    {
        <h4 class="bg-light text-center p-3">@TempData["msg"]</h4>
    }
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
</body>
</html>